#include "includes.h"

void LED_init(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOEEN;
	tmpio = RCC->AHBENR & RCC_AHBENR_GPIOEEN;
	(void)tmpio;
	
	InitPin(LED_port, LED0_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
	InitPin(LED_port, LED1_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
	InitPin(LED_port, LED2_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
	InitPin(LED_port, LED3_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
	InitPin(LED_port, LED4_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
	InitPin(LED_port, LED5_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
	InitPin(LED_port, LED6_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
	InitPin(LED_port, LED7_pin, GPIO_MODE_OUTPUT, GPIO_TYPE_PP, GPIO_SPEED_LOW, GPIO_PUPD_NONE);
}

void LED_set(uint8_t leds)
{
	LED_port->BRR = ((~leds) & 0xFF) << LED0_pin;
	LED_port->BSRR = leds << LED0_pin;
}